//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaPuntoVentaMaderas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaseDatosInventarioMaderaV8Entities : DbContext
    {
        public BaseDatosInventarioMaderaV8Entities()
            : base("name=BaseDatosInventarioMaderaV8Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientesSet> ClientesSet { get; set; }
        public virtual DbSet<ComprasSet> ComprasSet { get; set; }
        public virtual DbSet<DetalleComprasSet> DetalleComprasSet { get; set; }
        public virtual DbSet<DetalleVentasSet> DetalleVentasSet { get; set; }
        public virtual DbSet<MaderasSet> MaderasSet { get; set; }
        public virtual DbSet<PrecioCompraProveedorSet> PrecioCompraProveedorSet { get; set; }
        public virtual DbSet<PrecioVentaClienteSet> PrecioVentaClienteSet { get; set; }
        public virtual DbSet<ProveedoresSet> ProveedoresSet { get; set; }
        public virtual DbSet<RegistroAbonoClientesSet> RegistroAbonoClientesSet { get; set; }
        public virtual DbSet<RegistroAbonoProveedorSet> RegistroAbonoProveedorSet { get; set; }
        public virtual DbSet<TipoPagoSet> TipoPagoSet { get; set; }
        public virtual DbSet<UsuariosSet> UsuariosSet { get; set; }
        public virtual DbSet<VentasSet> VentasSet { get; set; }
    }
}
